application: radiohead-or-horse-ebooks
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /get_more_quotes
  script: rohe.py
  login: admin

- url: /.*
  script: rohe.py
