application: radiohead-or-horse-ebooks
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /what.html
  static_files: what.html
  upload: what.html

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /get_more_quotes
  script: rohe.py
  login: admin

- url: /.*
  script: rohe.py
